#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

void solve(long long A, long long B) {
  std::cout << A * B - A - B + 1 << std::endl;

  return;
}

// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
int main() {
  long long A;
  std::scanf("%lld", &A);
  long long B;
  std::scanf("%lld", &B);
  solve(A, B);
  return 0;
}
