#!/usr/bin/env python3
import sys


def solve(H: int, W: int, S: "List[List[str]]"):
    for i in range(0, H):
        for j in range(0, W - 4):
            if ([S[i][j], S[i][j + 1], S[i][j + 2], S[i][j + 3], S[i][j + 4]] == ['s', 'n', 'u', 'k', 'e']):
                print(f"{i + 1} {j + 1}")
                print(f"{i + 1} {j + 2}")
                print(f"{i + 1} {j + 3}")
                print(f"{i + 1} {j + 4}")
                print(f"{i + 1} {j + 5}")

                return
            
            if ([S[i][j + 4], S[i][j + 3], S[i][j + 2], S[i][j + 1], S[i][j]] == ['s', 'n', 'u', 'k', 'e']):
                print(f"{i + 1} {j + 5}")
                print(f"{i + 1} {j + 4}")
                print(f"{i + 1} {j + 3}")
                print(f"{i + 1} {j + 2}")
                print(f"{i + 1} {j + 1}")

                return

    for i in range(0, H - 4):
        for j in range(0, W):
            if ([S[i][j], S[i + 1][j], S[i + 2][j], S[i + 3][j], S[i + 4][j]] == ['s', 'n', 'u', 'k', 'e']):
                print(f"{i + 1} {j + 1}")
                print(f"{i + 2} {j + 1}")
                print(f"{i + 3} {j + 1}")
                print(f"{i + 4} {j + 1}")
                print(f"{i + 5} {j + 1}")

                return

            if ([S[i + 4][j], S[i + 3][j], S[i + 2][j], S[i + 1][j], S[i][j]] == ['s', 'n', 'u', 'k', 'e']):
                print(f"{i + 5} {j + 1}")
                print(f"{i + 4} {j + 1}")
                print(f"{i + 3} {j + 1}")
                print(f"{i + 2} {j + 1}")
                print(f"{i + 1} {j + 1}")

                return
            
    for i in range(0, H - 4):
        for j in range(0, W - 4):
            if ([S[i][j], S[i + 1][j + 1], S[i + 2][j + 2], S[i + 3][j + 3], S[i + 4][j + 4]] == ['s', 'n', 'u', 'k', 'e']):
                print(f"{i + 1} {j + 1}")
                print(f"{i + 2} {j + 2}")
                print(f"{i + 3} {j + 3}")
                print(f"{i + 4} {j + 4}")
                print(f"{i + 5} {j + 5}")

                return
            
            if ([S[i + 4][j + 4], S[i + 3][j + 3], S[i + 2][j + 2], S[i + 1][j + 1], S[i][j]] == ['s', 'n', 'u', 'k', 'e']):
                print(f"{i + 5} {j + 5}")
                print(f"{i + 4} {j + 4}")
                print(f"{i + 3} {j + 3}")
                print(f"{i + 2} {j + 2}")
                print(f"{i + 1} {j + 1}")

                return

    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    H = int(next(tokens))  # type: int
    W = int(next(tokens))  # type: int
    S = [list(next(tokens)) for _ in range(H)]  # type: "List[List[str]]"
    solve(H, W, S)

if __name__ == '__main__':
    main()
