#!/usr/bin/env python3
import sys


YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(H, W, A, B):
    for i in range(H):
        for j in range(W):
            if [x[j:] + x[:j] for x in A[i:] + A[:i]] == B:
                print(YES)

                return

    print(NO)

    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    H = int(next(tokens))
    W = int(next(tokens))
    A = [list(next(iterate_tokens())) for _ in range(H)]
    B = [list(next(iterate_tokens())) for _ in range(H)]
    solve(H, W, A, B)


if __name__ == '__main__':
    main()
