#!/usr/bin/env python3
import sys
import itertools


def solve(N: int, S: str):
    if '-' in S and 'o' in S:
        print(max([len(list(g)) for k, g in itertools.groupby(S) if k == 'o']))
    else:
        print(-1)

    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    solve(N, S)


if __name__ == '__main__':
    main()
